# Generated by Django 4.0.6 on 2022-07-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MACDPara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sma', models.SmallIntegerField(default=20)),
                ('lma', models.SmallIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4, unique=True)),
                ('bm', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='benchmark')),
            ],
        ),
        migrations.CreateModel(
            name='StrList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11)),
                ('investage', models.SmallIntegerField()),
                ('asset', models.DecimalField(decimal_places=2, max_digits=12)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('risktolerance', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StrInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateField()),
                ('endtime', models.DateField()),
                ('stopgainratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stoplossratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('strid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.strlist', verbose_name='strategyid')),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.IntegerField()),
                ('ctime', models.DateField(verbose_name='closetime')),
                ('interval', models.SmallIntegerField(choices=[(0, '1d'), (1, '5d'), (2, '1mo'), (3, '1y')], default=0)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.stockinfo', verbose_name='stockid')),
            ],
        ),
        migrations.CreateModel(
            name='MACDBestPara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sma', models.SmallIntegerField(default=20)),
                ('lma', models.SmallIntegerField(default=60)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.stockinfo', verbose_name='stockid')),
            ],
        ),
        migrations.CreateModel(
            name='BTInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('startcash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ret', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='return')),
                ('paraid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.strinfo', verbose_name='strategyid')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.stockinfo', verbose_name='stockid')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='userid')),
            ],
        ),
        migrations.CreateModel(
            name='BSInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'buy'), (1, 'sell')], default=0)),
                ('time', models.DateField()),
                ('share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.stockinfo', verbose_name='stockid')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='userid')),
            ],
        ),
    ]
