# Generated by Django 4.0.6 on 2022-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='createtime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
