# Generated by Django 4.0.6 on 2022-07-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_btinfo_startcash_remove_userinfo_lma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinfo',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
