# Generated by Django 4.0.6 on 2022-07-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_btinfo_alpha_btinfo_share_btinfo_sharpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsinfo',
            name='btid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.btinfo', verbose_name='backtestid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='btinfo',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='btinfo',
            name='sharpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
