# Generated by Django 4.0.6 on 2022-07-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_bsinfo_btid_alter_btinfo_alpha_alter_btinfo_sharpe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsinfo',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='bsinfo',
            name='uid',
        ),
    ]
