# Generated by Django 4.0.6 on 2022-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_newsinfo_stockinfo_beta_stockinfo_marketcap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='emo',
            field=models.SmallIntegerField(choices=[(0, 'negative'), (1, 'neutral'), (2, 'positive')], default=1, verbose_name='emotion'),
        ),
    ]
