# Generated by Django 4.0.6 on 2022-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_newsinfo_emo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsconn',
            name='nid',
        ),
        migrations.AddField(
            model_name='newsconn',
            name='emo',
            field=models.SmallIntegerField(choices=[(0, 'negative'), (1, 'neutral'), (2, 'positive')], default=1, verbose_name='emotion'),
        ),
        migrations.AddField(
            model_name='newsconn',
            name='text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsInfo',
        ),
    ]
