# Generated by Django 4.0.6 on 2022-07-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_remove_newsconn_nid_newsconn_emo_newsconn_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsConn',
            new_name='NewsInfo',
        ),
    ]
